### ISSUE TITLE
“Upload from Gallery” Can I remove this?

### ISSUE THREAD

**Issue by Patrick386** [mohesu/barcode_scanner#116]
“Upload from Gallery” Can I remove this?
![final](https://github.com/mohesu/barcode_scanner/assets/49754877/7eb1e89a-2bb0-4a1e-8f84-ae0cd38dd550)

**Comment by rvndsngwn** [comment]
I'll added this option soon

**Comment by rvndsngwn** [comment]
Hi @Patrick386 
hide gallery button option has been added.

**Comment by Patrick386** [comment]
> Hi @Patrick386 hide gallery button option has been added.

Thank you for your quick support.
