### ISSUE TITLE
how to disable to read QRcode ?

### ISSUE THREAD

**Issue by DevMansoor** [mohesu/barcode_scanner#117]
I only want to read bar code so how can I disable QR code?

**Comment by rvndsngwn** [comment]
Hi @DevMansoor You can use a validator function for that.

**Comment by DevMansoor** [comment]
Can you give example ? i was trying but couldn't achieve this.
Thanks

**Comment by DevMansoor** [comment]
I was using this code but still it is reading QR code
` validator: (value) {
        for (var barcode in value.barcodes) {
          if (barcode.format == BarcodeFormat.qrCode) {
            return false;
          }
        }
        return true;
      },`

**Comment by rvndsngwn** [comment]
You can also use the 'formats: [BarcodeFormat.all]' in the controller.

**Comment by DevMansoor** [comment]
Thanks, This works , I have excluded  BarcodeFormat.qrCode from formats.
