### ISSUE TITLE
iOS   'GTMDefines.h' file not found

### ISSUE THREAD

**Issue by shichunlei** [mohesu/barcode_scanner#124]
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'GTMDefines.h' file not found
/Users/mac104/workspace/***/ios/Pods/GoogleToolboxForMac/Foundation/GTMNSData+zlib.h:19:8

Error launching application on iPhone.

flutter doctor:

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.1.1 23B81 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)

**Comment by rvndsngwn** [comment]
Hi @shichunlei this issue has been resolved with latest version.
