### ISSUE TITLE
Dependency on mobile_scanner is causing issues on iOS

### ISSUE THREAD

**Issue by AbelTarazona** [mohesu/barcode_scanner#127]
Despite using the most recent version of the package (5.2.1) you can see that it is pointing to Google Data Transport, which is lower than the one used by Firebase.

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
      In Podfile:

        firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.1.2, which depends on
          Firebase/Crashlytics (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseCrashlytics (~> 11.0.0) was resolved to 11.0.0, which depends on
              GoogleDataTransport (~> 10.0)

        mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
          GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
            GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
              MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
                GoogleDataTransport (< 10.0, >= 9.4.1)

**Comment by YoussefShehab** [comment]
@AbelTarazona 
Did you find any solution ?

**Comment by rvndsngwn** [comment]
> 
> 
> 
> ```
> firebase_core: 3.3.0
> ```
> 
> (Note the missing `^`)
> 
> 
> ```
> rm podfile.lock
> pod install --repo-update
> ```
