### ISSUE TITLE
Outdate of the readme

### ISSUE THREAD

**Issue by chungxon** [mohesu/barcode_scanner#130]
In your readme file, there is a section like this
> If you don't set allowDuplicates to false, you can scan multiple times in a very short time, causing things like pop() to fire multiple times.

Because the author removed `allowDuplicates` and replaced it with the `MobileScannerSpeed` enum. Ref https://github.com/juliansteenbakker/mobile_scanner/issues/547

Please update your guide. Thanks!

**Comment by rvndsngwn** [comment]
Hi @chungxon readme has been updated.

**Comment by chungxon** [comment]
Thank you!
