### ISSUE TITLE
Conflicts with all versions of cloud firestore

### ISSUE THREAD

**Issue by Ademie** [mohesu/barcode_scanner#131]
[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.4.4, which depends on
      Firebase/Firestore (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseFirestore (~> 11.2.0) was resolved to 11.2.0, which depends on
          FirebaseFirestoreInternal (= 11.2.0) was resolved to 11.2.0, which depends on
            nanopb (~> 3.30910.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)

**Comment by rvndsngwn** [comment]
Hi @Ademie this issue has been resolved with latest version.
