### ISSUE TITLE
Cut Out Size should be nullable or the condition for this should  accepted 0 AND  Need provision to hide camera switch button 

### ISSUE THREAD

**Issue by Abhinav-Satija** [mohesu/barcode_scanner#32]
original code   assert(
        (cutOutWidth == null && cutOutHeight == null) ||
            (cutOutSize == null && cutOutWidth != null && cutOutHeight != null),
        'Use only cutOutWidth and cutOutHeight or only cutOutSize');
  }

working one  assert(
        (cutOutWidth == null && cutOutHeight == null) ||
            (cutOutSize == 0.0 && cutOutWidth != null && cutOutHeight != null),
        'Use only cutOutWidth and cutOutHeight or only cutOutSize');
  }

can you update this release to another version?

**Comment by rvndsngwn** [comment]
Hi @Abhinav-Satija thanks for using this package.

Yes, I'll be improving this package always. I appreciate your suggestion.

**Comment by rvndsngwn** [comment]
0.0.4 https://pub.dev/packages/ai_barcode_scanner the latest version which fixes this issue.
