### ISSUE TITLE
app crashing 

### ISSUE THREAD

**Issue by Abhinav-Satija** [mohesu/barcode_scanner#34]
When we put the camera in front of more than one barcode, it begins to crash.

[scanner crash logs.txt](https://github.com/mohesu/barcode_scanner/files/10822719/scanner.crash.logs.txt)

https://user-images.githubusercontent.com/10865512/221144835-8964f0ee-8e44-4e11-b15b-e22d32ab95f4.mp4

**Comment by rvndsngwn** [comment]
Thanks for using this package, @Abhinav-Satija.

```
      controller: MobileScannerController(
        detectionSpeed: DetectionSpeed.noDuplicates,
      ),
```
You need to add a controller to your code.

This issue is the same as well #32.

**Comment by rvndsngwn** [comment]
I hope that the issue has been resolved, and therefore, I will proceed to close it. However, if you still encounter the same issue, please do not hesitate to reopen it.
