### ISSUE TITLE
Example app giving permission denied error on macOS.

### ISSUE THREAD

**Issue by BirjuVachhani** [mohesu/barcode_scanner#37]
The library on pub.dev says it supports macOS but when I run the example app on macOS, it throws permission denied exception.

**Comment by rvndsngwn** [comment]
@BirjuVachhani Thanks for using this package, I'll investigate and resolve as soon as possible.

**Comment by rvndsngwn** [comment]
Hi @BirjuVachhani, Ensure that you granted camera permission in XCode -> Signing & Capabilities:


![](https://user-images.githubusercontent.com/24459435/193464115-d76f81d0-6355-4cb2-8bee-538e413a3ad0.png)

https://pub.dev/packages/ai_barcode_scanner#macos
