### ISSUE TITLE
Picks Wide angle camera on iPhone (which is low-res) - having problems scanning barcodes

### ISSUE THREAD

**Issue by siranov** [mohesu/barcode_scanner#55]
The plugin works flawlessly on Android, thank you very much!

Unfortunately, on iPhones it starts with wide angle camera so it has hard time scanning the barcode. Can you please look into that or let me know how I can fix that? I would want it to start with primary narrow angle camera which is higher res.

**Comment by rvndsngwn** [comment]
I'm glad this package was useful for you @siranov 
Let me check this issue.
