### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by PetroShylaiev** [mohesu/barcode_scanner#76]
In the code I see that we set

 /// keeps the app in portrait mode
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    
 Is it possible to make it optional and injected as a parameter in `AiBarcodeScanner`? We have an app that is always landscape

**Comment by rvndsngwn** [comment]
Hi @PetroShylaiev Thanks for creating an issue.

In the next version, I'll make this optional.
