### ISSUE TITLE
Camera Pops so many screen!!

### ISSUE THREAD

**Issue by Adarsh2002014** [mohesu/barcode_scanner#80]
I have used scanner but it pop's the screen after scanning.
My code for the following is ...
                    try {
                      await Navigator.of(context).push(
                        MaterialPageRoute(
                          builder: (context) => AiBarcodeScanner(
                            canPop: false,
                            allowDuplicates: false,
                            onScan: (String value) {
                              print(value);
                              barcode = value;
                              barcodeValue.text = barcode;
                              Navigator.of(context).pop();
                              // setState(() {
                              //
                              // });
                            },
                          ),
                        ),
                      );
                    } catch (e) {
                      print(e);
                    }
                  },

Pls help

**Comment by rvndsngwn** [comment]
Hi @Adarsh2002014, Thanks for creating an issue.

use the controller for no duplicates scans instead of `allowDuplicates: false`
```dart
      controller: MobileScannerController(
        detectionSpeed: DetectionSpeed.noDuplicates,
      ),
```

check the context is mounted or not at `Navigator.of(context).pop()`

```dart
if(context.mounted){
Navigator.of(context).pop();
}
```

**Comment by Adarsh2002014** [comment]
Thanks @rvndsngwn. Right now everything is working fine after rewriting code as per your suggestion. If there anything else i will let you know afterwards.👍👍
